# H2 Database
# JDBC URL: jdbc:h2:file:C:/temp/test
spring.datasource.url=jdbc:h2:file:C:/temp/test;DB_CLOSE_DELAY=-1
# ????? ????????
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JSON
spring.jackson.date-format=yyyy-MM-dd

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

server.port=8080